language: ruby
rvm:
  - ruby-head
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - jruby-19mode

sudo: false
cache: bundler

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem update bundler
